export interface CDPatientInterface {
  health_id: string;
  active: boolean;
  address_line: string;
  area_mouja: string;
  assigned_by: string;
  bin_brn: null | string;
  blood_group: null | string;
  city_corporation_id: string;
  confidential: boolean;
  country_code: string;
  created_at: TimeUuid;
  created_by: string;
  date_of_birth: Date;
  date_of_death: null | Date;
  disability: null | string;
  district_id: string;
  division_id: string;
  dob_type: string;
  edu_level: null | string;
  ethnicity: null | string;
  fathers_brn: string;
  fathers_given_name: string;
  fathers_name_bangla: string;
  fathers_nid: string;
  fathers_sur_name: string;
  fathers_uid: string;
  full_name_bangla: null | string;
  gender: string;
  given_name: string;
  hid_card_status: string;
  holding_number: string;
  household_code: null | string;
  marital_relations: null | string;
  marital_status: null | string;
  marriage_id: null | string;
  merged_with: null | string;
  mothers_brn: string;
  mothers_given_name: string;
  mothers_name_bangla: string;
  mothers_nid: string;
  mothers_sur_name: string;
  mothers_uid: string;
  national_id: null | string;
  nationality: string;
  occupation: null | string;
  pending_approvals: null | string;
  permanent_address_line: null | string;
  permanent_area_mouja: null | string;
  permanent_city_corporation_id: null | string;
  permanent_country_code: null | string;
  permanent_district_id: null | string;
  permanent_division_id: null | string;
  permanent_holding_number: null | string;
  permanent_post_code: null | string;
  permanent_post_office: null | string;
  permanent_rural_ward_id: null | string;
  permanent_street: null | string;
  permanent_union_or_urban_ward_id: null | string;
  permanent_upazila_id: null | string;
  permanent_village: null | string;
  phone_no: null | string;
  phone_number_area_code: null | string;
  phone_number_country_code: null | string;
  phone_number_extension: null | string;
  place_of_birth: null | string;
  post_code: string;
  post_office: string;
  primary_contact: string;
  primary_contact_no: null | string;
  primary_contact_number_area_code: null | string;
  primary_contact_number_country_code: null | string;
  primary_contact_number_extension: null | string;
  relations: string;
  religion: null | string;
  rural_ward_id: string;
  status: string;
  street: string;
  sur_name: string;
  uid: null | string;
  union_or_urban_ward_id: string;
  upazila_id: string;
  updated_at: TimeUuid;
  updated_by: string;
  village: string;
}

export interface TimeUuid {
  buffer: Buffer;
}
