export interface AuthProfileInterface {
        name: String;
        id: String;
        catchment: string[];
}
export default interface AuthResponseInterface{
    code?:Number;
    status?:string;
    message?:string;
    data?: any;
    redirect?: string;
    access_token?: string;
    id?: Number;
    name?: String;
    name_bn?: String;
    email?: String;
    mobile?: String;
    group_ids?: Array<String>;
    group_names_formatted?: Array<String>;
    facility_agency_id?: Number;
    facility_agency_name?: String;
    ministry_id?: String;
    ministry_name?: String;
    provider_id?: String;
    hid?: String;
    facility_id?: String;
    facility_department_ids?: String;
    facility_department_names_formatted?: String;
    division_id?: String;
    division_name?: String;
    district_id?: String;
    district_name?: String;
    upazila_id?: String;
    upazila_name?: String;
    paurasava_id?: String;
    paurasava_name?: String;
    union_id?: String;
    union_name?: String;
    ward_id?: String;
    ward_name?: String;
    catchments?: String;
    transfer_authority_ids?: String;
    leave_authority_ids?: String;
    training_authority_ids?: String;
    post_creation_authority_ids?: String;
    support_ticket_category_ids?: String;
    is_active?: Number;
    groups?: Array<String>;
    activated?: Boolean;
    profiles?: Array<AuthProfileInterface>;
}