import { FacilityAdminInterface } from "@utils/interfaces/DataModels/FacilityAdminInterface";
import { FacilityInterface } from "@utils/interfaces/DataModels/FacilityInterfaces";

export interface CreateAndUpdatedByPatientInterface {
    facility: FacilityInterface | null;
    provider: string | null;
    admin: FacilityAdminInterface | null;
  };

export interface ESPatientInterface {
  health_id: string;
  active: boolean | null;
  address_line: string | null;
  area_mouja: string | null;
  assigned_by: string | null;
  bin_brn: string | null;
  blood_group: string | null;
  city_corporation_id: string | null;
  confidential: boolean | null;
  country_code: string | null;
  created_at: any;
  created_by: CreateAndUpdatedByPatientInterface;
  created_client_id: Number | null;
  created_facility_id: Number | null;
  date_of_birth: Date | null;
  date_of_death: Date | null;
  disability: string | null;
  district_id: Number | null;
  division_id: Number | null;
  dob_type: string | null;
  edu_level: string | null;
  ethnicity: string | null;
  fathers_brn: string | null;
  fathers_given_name: string | null;
  fathers_name_bangla: string | null;
  fathers_nid: string | null;
  fathers_sur_name: string | null;
  fathers_uid: string | null;
  full_name_bangla: string | null;
  gender: string | null;
  given_name: string | null;
  hid_card_status: string | null;
  holding_number: string | null;
  household_code: string | null;
  index_time: Date | null;
  index_updated_time: Date | null;
  marital_relations: string | null;
  marital_status: string | null;
  marriage_id: string | null;
  merged_with: string | null;
  mothers_brn: string | null;
  mothers_given_name: string | null;
  mothers_name_bangla: string | null;
  mothers_nid: string | null;
  mothers_sur_name: string | null;
  mothers_uid: string | null;
  national_id: string | null;
  nationality: string | null;
  occupation: string | null;
  pending_approvals: string | null;
  permanent_address_line: string | null;
  permanent_area_mouja: string | null;
  permanent_city_corporation_id: string | null;
  permanent_country_code: string | null;
  permanent_district_id: Number | null;
  permanent_division_id: Number | null;
  permanent_holding_number: string | null;
  permanent_post_code: string | null;
  permanent_post_office: string | null;
  permanent_rural_ward_id: Number | null;
  permanent_street: string | null;
  permanent_union_or_urban_ward_id: Number | null;
  permanent_upazila_id: Number | null;
  permanent_village: string | null;
  phone_no: string | null;
  phone_number_area_code: string | null;
  phone_number_country_code: string | null;
  phone_number_extension: string | null;
  place_of_birth: string | null;
  post_code: string | null;
  post_office: string | null;
  primary_contact: string | null;
  primary_contact_no: string | null;
  primary_contact_number_area_code: string | null;
  primary_contact_number_country_code: string | null;
  primary_contact_number_extension: string | null;
  relations: string | null;
  religion: string | null;
  rural_ward_id: Number | null;
  status: string | null;
  street: string | null;
  sur_name: string | null;
  uid: string | null;
  union_or_urban_ward_id: Number | null;
  upazila_id: Number | null;
  updated_facility_id: Number | null;
  updated_at: any
  updated_by: CreateAndUpdatedByPatientInterface;
  village: string | null;
  user_photo?: string | null;
}
